#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Sat Sep 30 14:42:15 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.FRAME_TOOL_WINDOW | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.STAY_ON_TOP | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_3 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN | wx.TAB_TRAVERSAL)
        self.label_11 = wx.StaticText(self.panel_3, wx.ID_ANY, ("Vault stats generator"))
        self.labelVersion = wx.StaticText(self.panel_3, wx.ID_ANY, ("version 1.0"))
        self.label_13 = wx.StaticText(self.panel_3, wx.ID_ANY, ("By Valefort"))
        self.labelUpdate = wx.StaticText(self.panel_3, wx.ID_ANY, ("Last Update : 30/09/2017 15:00 "), style=wx.ALIGN_RIGHT)
        self.buttonClose = wx.Button(self, wx.ID_ANY, ("Close"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(("frame_1"))
        self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_3DFACE))
        self.label_11.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_11.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Arial"))
        self.labelVersion.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_13.SetForegroundColour(wx.Colour(0, 0, 0))
        self.labelUpdate.SetForegroundColour(wx.Colour(0, 0, 0))
        self.buttonClose.SetMinSize((60, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_18 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 5)
        grid_sizer_22 = wx.FlexGridSizer(8, 1, 0, 0)
        grid_sizer_22.Add(self.label_11, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 10)
        grid_sizer_22.Add(self.labelVersion, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 10)
        grid_sizer_22.Add(self.label_13, 0, wx.LEFT, 10)
        grid_sizer_22.Add(self.labelUpdate, 0, wx.ALIGN_RIGHT | wx.RIGHT | wx.TOP, 7)
        grid_sizer_22.Add((10, 10), 0, wx.FIXED_MINSIZE, 0)
        self.panel_3.SetSizer(grid_sizer_22)
        grid_sizer_22.AddGrowableRow(5)
        grid_sizer_22.AddGrowableCol(0)
        grid_sizer_18.Add(self.panel_3, 1, wx.ALL | wx.EXPAND, 5)
        grid_sizer_2.Add(self.buttonClose, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_18.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_18)
        grid_sizer_18.Fit(self)
        grid_sizer_18.AddGrowableRow(1)
        grid_sizer_18.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

# end of class MyFrame
